# Assignment 7 - Conference

### Imports

## <u>Stage 1</u>: Checking Initial Model Feasibility 

The objective function can be something as simple as 0 now given that we are just checking if at least one feasible solution exists given all of our stiplated constraints.

The data in the `band_info_cleaned.csv` file will be useful.

In [1]:
import pandas as pd
df=pd.read_csv('speaker_info_cleaned.csv')
df

,Speaker,Tier,Unavailable_Timeslots,Present_After,Time Slot Preference
0,1,Keynote,"4, 5, 6, 7, 8, 9, 10",6.0,3
1,2,Keynote,"1, 5, 6, 7, 8, 9, 10",NaN,4
2,3,Keynote,"1, 2, 3, 4, 8, 9, 10",10.0,6
3,4,Keynote,"1, 2, 3, 4, 5, 9, 10",NaN,7
4,5,Keynote,"4, 5, 6, 7, 8, 9, 10",NaN,4
5,6,Regular,"3, 4, 5, 6, 7, 8, 9, 10",NaN,2
6,7,Regular,"1, 2, 5, 6, 7, 8, 9, 10",NaN,3
7,8,Regular,"1, 2, 3, 4, 7, 8, 9, 10",NaN,6
8,9,Regular,"1, 2, 3, 4, 5, 6, 9, 10",NaN,7
9,10,Regular,"1, 2, 3, 7, 8, 9, 10",NaN,9
10,11,Regular,"4, 5, 6, 7, 8, 9, 10",NaN,1
11,12,Regular,"1, 5, 6, 7, 8, 9, 10",NaN,2
12,13,Regular,"1, 2, 3, 4, 8, 9, 10",NaN,5
13,14,Regular,"1, 2, 3, 4, 5, 9, 10",NaN,7
14,15,Regular,"1, 2, 3, 4, 5, 6, 7",NaN,8
15,16,Regular,"5, 6, 7, 8, 9, 10",NaN,2
16,17,Regular,"1, 6, 7, 8, 9, 10",NaN,3
17,18,Regular,"1, 2, 3, 4, 5, 9, 10",NaN,6
18,19,Regular,"4, 5, 6, 7, 8, 9, 10",NaN,1
19,20,Regular,"1, 2, 6, 7, 8, 9, 10",NaN,5
20,21,Regular,"1, 2, 3, 4, 5, 9, 10",NaN,7
21,22,Regular,"1, 2, 3, 4, 5, 6, 7, 8",NaN,9
22,23,Regular,"3, 4, 5, 6, 7, 8, 9, 10",NaN,2
23,24,Regular,"1, 5, 6, 7, 8, 9, 10",NaN,4
24,25,Regular,"1, 2, 3, 4, 9, 10",NaN,6
25,26,Regular,"1, 2, 3, 4, 5, 10",NaN,8
26,27,Regular,"1, 5, 6, 7, 8, 9, 10",NaN,2
27,28,Regular,"1, 2, 3, 7, 8, 9, 10",NaN,4
28,29,Regular,"1, 2, 3, 4, 5, 6, 10",NaN,7
29,30,Regular,"1, 2, 3, 4, 5, 6, 7, 8",NaN,9

#### <u>Hint #1</u>: Data Cleaning
The data cleaning steps in Stage 1 of the Unit 4 application will be really helpful here (especially the data cleaning that we performed on `df['day_off_requested_index']`). Pay close attention to the format values in your `Unavailable_Timeslots` column take on. Ideally they should be list of integers for easier indexing in your decision variables.

Check this to see what type of values they take on.

In [2]:
df['Unavailable_Timeslots'].loc[0]

'4, 5, 6, 7, 8, 9, 10'

## <u>Stage 2</u>: Relaxation - Not All Speakers Have to Present, Not all Rooms/Timeslots have to be Filled

## <u>Stage 3</u>: Some Speakers Get to Present More Than Once